### ISSUE TITLE
Upkeep for svglite (2024)

### ISSUE THREAD

**Issue by thomasp85** [r-lib/svglite#179]
### To begin

* [x] `pr_init("upkeep-2024-10")`

### Pre-history

* [ ] `usethis::use_readme_rmd()`
* [ ] `usethis::use_roxygen_md()`
* [ ] `usethis::use_github_links()`
* [ ] `usethis::use_pkgdown_github_pages()`
* [ ] `usethis::use_tidy_github_labels()`
* [ ] `usethis::use_tidy_style()`
* [ ] `urlchecker::url_check()`

### 2020

* [ ] `usethis::use_package_doc()`
* [ ] `usethis::use_testthat(3)`
* [ ] Align the names of `R/` files and `test/` files

### 2021

* [x] Remove check environments section from `cran-comments.md`
* [x] Use lifecycle instead of artisanal deprecation messages

### 2022

* [x] Handle and close any still-open `master` --> `main` issues
* [x] `usethis:::use_codecov_badge("r-lib/svglite")`
* [x] Update pkgdown site using instructions at <https://tidytemplate.tidyverse.org>
* [x] Update lifecycle badges with more accessible SVGs: `usethis::use_lifecycle()`

### 2023

* [x] Update copyright holder in DESCRIPTION: `person("Posit Software, PBC", role = c("cph", "fnd"))`
* [x] Run `devtools::document()` to re-generate package-level help topic with DESCRIPTION changes
* [x] `usethis::use_tidy_logo(); pkgdown::build_favicons(overwrite = TRUE)`
* [x] `usethis::use_tidy_coc()`
* [x] Use `pak::pak("r-lib/svglite")` in README
* [ ] Consider running `usethis::use_tidy_dependencies()` and/or replace compat files with `use_standalone()`
* [x] Use cli errors or [file an issue](new) if you don't have time to do it now
* [x] `usethis::use_standalone("r-lib/rlang", "types-check")` instead of home grown argument checkers;
or [file an issue](new) if you don't have time to do it now
* [ ] Add alt-text to pictures, plots, etc; see https://posit.co/blog/knitr-fig-alt/ for examples

### 2024

* [x] Review pkgdown output to find missing alt-text (perennial issue)
* [x] Switch to new quarto chunk style: https://github.com/r-lib/usethis/issues/1913
* [x] Switch to `expect_snasphot(error = TRUE)` for class-less `expect_error()`: https://github.com/r-lib/usethis/issues/1918 
* [x] Record upkeep date (https://github.com/r-lib/usethis/issues/1916)

### To finish

* [x] `usethis::use_package("R", "Depends", "4.0")`
* [x] `usethis::use_tidy_description()`
* [x] `usethis::use_tidy_github_actions()`
* [x] `devtools::build_readme()`
* [ ] [Re-publish released site](https://pkgdown.r-lib.org/dev/articles/how-to-update-released-site.html) if needed

<sup>Created on 2024-10-23 with `usethis::use_tidy_upkeep_issue()`, using [usethis v3.0.0.9000](https://usethis.r-lib.org)</sup>
